services:
  - type: web
    name: phishintel-backend
    env: python
    runtime: python3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: URLSCAN_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://phish-intel.vercel.app,http://localhost:5173,http://127.0.0.1:5173"
      - key: PORT
        value: "5000"
    healthCheckPath: /api/health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
    disk:
      name: data
      mountPath: /opt/render/project/src/Data
      sizeGB: 1
